name: Linter

on:
  push:
    branshes: [ main ]
  pull_request:
    branshes: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      
      - name: Run linter
        run: make lint
